# Generated by Django 5.2.1 on 2025-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='A6F5F7BC', max_length=8, unique=True),
        ),
    ]
