# Generated by Django 5.2.1 on 2025-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='9C152AAC', max_length=8, unique=True),
        ),
    ]
