# Generated by Django 5.2.1 on 2025-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='6E9CFAF8', max_length=8, unique=True),
        ),
    ]
