# Generated by Django 5.2.1 on 2025-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='BC12A031', max_length=8, unique=True),
        ),
    ]
