# Generated by Django 5.2.1 on 2025-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_participant_role_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='A0F3B036', max_length=8, unique=True),
        ),
    ]
