# Generated by Django 5.2.1 on 2025-05-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='68B39E9D', max_length=8, unique=True),
        ),
    ]
