# Generated by Django 5.2.1 on 2025-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='C0AF2C7C', max_length=8, unique=True),
        ),
    ]
