# Generated by Django 5.2.1 on 2025-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='2884C223', max_length=8, unique=True),
        ),
    ]
