# Generated by Django 5.2.1 on 2025-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='A37CB9FC', max_length=8, unique=True),
        ),
    ]
