# Generated by Django 5.2.1 on 2025-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='DAA8889B', max_length=8, unique=True),
        ),
    ]
