# Generated by Django 3.2.25 on 2025-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='F8146F6D', max_length=8, unique=True),
        ),
    ]
