# Generated by Django 3.2.25 on 2025-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='9C8EC8F4', max_length=8, unique=True),
        ),
    ]
