# Generated by Django 3.2.25 on 2025-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='BCAC77BB', max_length=8, unique=True),
        ),
    ]
